name: notmag
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39827
title: this is NOT magenta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2c2c2c'
    - '#656565'
    - '#a8a8a8'
  brandStrength: 0.4375
  lightness: 0.544871993130073
  saturation: 0
  rhythmicContrast: 0.21196918585337698
purpose: []
